### ISSUE TITLE
Dynamic crictl_arch variables

### ISSUE THREAD

**Issue by RS185734** [darkwizard242/ansible-role-crictl#9]
crictl_arch shall be set from facts, folks use Raspberry nowadays with other amd64 systems.

**Comment by darkwizard242** [comment]
Hi @RS185734  - Multiple architecture support has now been added and released as version [2.6.0](https://github.com/darkwizard242/ansible-role-crictl/releases/tag/2.6.0) of the role, changes done in PR #11 . Please attempt at using latest/[2.6.0](https://github.com/darkwizard242/ansible-role-crictl/releases/tag/2.6.0) of the role.

Closing the issue as it has been addressed.
